import random

dummy_data_list = [
        {
        'commonName': 'Kangaroo',
        'scientificName': 'Macropus rufus',
        'populationSize': 5000000,
        'description': 'The kangaroo is an iconic Australian marsupial.',
        'estimatedExtinctionDate': '2050-01-01',
        'closestNeighbourCommonName': 'Wallaby',
        'closestNeighbourScientificName': 'Macropus_eugenii',
        'region': 'NewSouthWales',
        'latitude': '-33.8688',  # Latitude for Sydney, Australia
        'longitude': '151.2093',  # Longitude for Sydney, Australia
        'threatName': 'Habitat Loss',
        'threatDescription': 'Loss of natural habitats due to urbanization.',
        'severity': 3,
        'organizationName': 'Australian Wildlife Conservation Society',
        'projectDescription': 'Conservation project for kangaroo preservation.',
        'startDate': '2022-01-01',
        'endDate': '2025-01-01',
        'cloclatitude': '-33.8688',  # Latitude for Sydney, Australia
        'cloclongitude': '151.2093',  # Longitude for Sydney, Australia
        'cloccountry': 'Australia',
        'clocregion': 'NewSouthWales',
        'conservationPark': 'Outback National Park'
    },
    {
        'commonName': 'Koala',
        'scientificName': 'Phascolarctos cinereus',
        'populationSize': 80000,
        'description': 'The koala is an arboreal herbivorous marsupial native to Australia.',
        'estimatedExtinctionDate': '2040-01-01',
        'closestNeighbourCommonName': 'Possum',
        'closestNeighbourScientificName': 'Trichosurus_vulpecula',
        'region': 'Queensland',
        'latitude': '-27.4698',  # Latitude for Brisbane, Australia
        'longitude': '153.0251',  # Longitude for Brisbane, Australia
        'threatName': 'Bushfires',
        'threatDescription': 'Increasing frequency of bushfires affecting habitats.',
        'severity': 4,
        'organizationName': 'Australian Koala Foundation',
        'projectDescription': 'Conservation project for koala habitats.',
        'startDate': '2022-01-01',
        'endDate': '2024-01-01',
        'cloclatitude': '-27.4698',  # Latitude for Brisbane, Australia
        'cloclongitude': '153.0251',  # Longitude for Brisbane, Australia
        'cloccountry': 'Australia',
        'clocregion': 'Queensland',
        'conservationPark': 'Eucalyptus Grove Conservation Reserve'
    },
    {
        'commonName': 'Emu',
        'scientificName': 'Dromaius novaehollandiae',
        'populationSize': 120000,
        'description': 'The emu is the world\'s second-largest bird.',
        'estimatedExtinctionDate': '2035-01-01',
        'closestNeighbourCommonName': 'Cassowary',
        'closestNeighbourScientificName': 'Casuarius_casuarius',
        'region': 'Victoria',
        'latitude': '-37.8136',  # Latitude for Melbourne, Australia
        'longitude': '144.9631',  # Longitude for Melbourne, Australia
        'threatName': 'Climate Change',
        'threatDescription': 'Changing climate affecting food sources and breeding.',
        'severity': 2,
        'organizationName': 'Australian Bird Conservation Society',
        'projectDescription': 'Conservation project for emu habitats.',
        'startDate': '2022-01-01',
        'endDate': '2023-12-31',
        'cloclatitude': '-37.8136',  # Latitude for Melbourne, Australia
        'cloclongitude': '144.9631',  # Longitude for Melbourne, Australia
        'cloccountry': 'Australia',
        'clocregion': 'Victoria',
        'conservationPark': 'Open Plains Nature Reserve'
    },
    {
        'commonName': 'Wombat',
        'scientificName': 'Vombatus ursinus',
        'populationSize': 30000,
        'description': 'The wombat is a herbivorous marsupial native to Australia.',
        'estimatedExtinctionDate': '2045-01-01',
        'closestNeighbourCommonName': 'Kangaroo',
        'closestNeighbourScientificName': 'Macropus_rufus',
        'region': 'Tasmania',
        'latitude': '-42.8821',  # Latitude for Hobart, Australia
        'longitude': '147.3272',  # Longitude for Hobart, Australia
        'threatName': 'Invasive Species',
        'threatDescription': 'Introduction of invasive species impacting wombat habitats.',
        'severity': 3,
        'organizationName': 'Tasmanian Wildlife Preservation Society',
        'projectDescription': 'Conservation project for wombat populations.',
        'startDate': '2022-01-01',
        'endDate': '2025-01-01',
        'cloclatitude': '-42.8821',  # Latitude for Hobart, Australia
        'cloclongitude': '147.3272',  # Longitude for Hobart, Australia
        'cloccountry': 'Australia',
        'clocregion': 'Tasmania',
        'conservationPark': 'Tasmanian Wilderness Sanctuary'
    },
    {
        'commonName': 'Cockatoo',
        'scientificName': 'Cacatua',
        'populationSize': 150000,
        'description': 'Cockatoos are a family of parrots native to Australia.',
        'estimatedExtinctionDate': '2030-01-01',
        'closestNeighbourCommonName': 'Galah',
        'closestNeighbourScientificName': 'Eolophus_roseicapilla',
        'region': 'WesternAustralia',
        'latitude': '-31.9505',  # Latitude for Perth, Australia
        'longitude': '115.8605',  # Longitude for Perth, Australia
        'threatName': 'Illegal Pet Trade',
        'threatDescription': 'Illegal capture and trade impacting cockatoo populations.',
        'severity': 4,
        'organizationName': 'Western Australian Avian Conservation',
        'projectDescription': 'Conservation project for cockatoo welfare.',
        'startDate': '2022-01-01',
        'endDate': '2024-01-01',
        'cloclatitude': '-31.9505',  # Latitude for Perth, Australia
        'cloclongitude': '115.8605',  # Longitude for Perth, Australia
        'cloccountry': 'Australia',
        'clocregion': 'WesternAustralia',
        'conservationPark': 'Eucalyptus Canopy Conservation Area'
    },
    {
        'commonName': 'Platypus',
        'scientificName': 'Ornithorhynchus anatinus',
        'populationSize': 10000,
        'description': 'The platypus is a unique egg-laying mammal native to Australia.',
        'estimatedExtinctionDate': '2055-01-01',
        'closestNeighbourCommonName': 'Echidna',
        'closestNeighbourScientificName': 'Tachyglossus_aculeatus',
        'region': 'SouthAustralia',
        'latitude': '-34.9285',  # Latitude for Adelaide, Australia
        'longitude': '138.6007',  # Longitude for Adelaide, Australia
        'threatName': 'Water Pollution',
        'threatDescription': 'Pollution of water sources impacting platypus habitats.',
        'severity': 3,
        'organizationName': 'South Australian Mammal Preservation',
        'projectDescription': 'Conservation project for platypus ecosystems.',
        'startDate': '2022-01-01',
        'endDate': '2023-12-31',
        'cloclatitude': '-34.9285',  # Latitude for Adelaide, Australia
        'cloclongitude': '138.6007',  # Longitude for Adelaide, Australia
        'cloccountry': 'Australia',
        'clocregion': 'SouthAustralia',
        'conservationPark': 'Murray River Conservation Reserve'
    },
        {
        'commonName': 'Cassowary',
        'scientificName': 'Casuarius casuarius',
        'populationSize': 5000,
        'description': 'Cassowaries are large, flightless birds native to the tropical forests of New Guinea and nearby islands.',
        'estimatedExtinctionDate': '2042-01-01',
        'closestNeighbourCommonName': 'Emu',
        'closestNeighbourScientificName': 'Dromaius_novaehollandiae',
        'region': 'Queensland',
        'latitude': '-27.4698',  # Latitude for Brisbane, Australia
        'longitude': '153.0251',  # Longitude for Brisbane, Australia
        'threatName': 'Deforestation',
        'threatDescription': 'Clearing of forests impacting cassowary habitats.',
        'severity': 4,
        'organizationName': 'Queensland Bird Conservation Alliance',
        'projectDescription': 'Conservation project for cassowary environments.',
        'startDate': '2022-01-01',
        'endDate': '2024-01-01',
        'cloclatitude': '-27.4698',  # Latitude for Brisbane, Australia
        'cloclongitude': '153.0251',  # Longitude for Brisbane, Australia
        'cloccountry': 'Australia',
        'clocregion': 'Queensland',
        'conservationPark': 'Tropical Rainforest Reserve'
    },
    {
        'commonName': 'Echidna',
        'scientificName': 'Tachyglossus aculeatus',
        'populationSize': 15000,
        'description': 'The echidna, also known as the spiny anteater, is one of the few monotremes.',
        'estimatedExtinctionDate': '2048-01-01',
        'closestNeighbourCommonName': 'Platypus',
        'closestNeighbourScientificName': 'Ornithorhynchus_anatinus',
        'region': 'SouthAustralia',
        'latitude': '-34.9285',  # Latitude for Adelaide, Australia
        'longitude': '138.6007',  # Longitude for Adelaide, Australia
        'threatName': 'Land Development',
        'threatDescription': 'Urban development impacting echidna habitats.',
        'severity': 2,
        'organizationName': 'South Australian Wildlife Preservation Society',
        'projectDescription': 'Conservation project for echidna populations.',
        'startDate': '2022-01-01',
        'endDate': '2025-01-01',
        'cloclatitude': '-34.9285',  # Latitude for Adelaide, Australia
        'cloclongitude': '138.6007',  # Longitude for Adelaide, Australia
        'cloccountry': 'Australia',
        'clocregion': 'SouthAustralia',
        'conservationPark': 'Adelaide Hills Wildlife Sanctuary'
    },
    {
        'commonName': 'Galah',
        'scientificName': 'Eolophus roseicapilla',
        'populationSize': 100000,
        'description': 'The galah is one of the most common and widespread cockatoos.',
        'estimatedExtinctionDate': '2033-01-01',
        'closestNeighbourCommonName': 'Cockatoo',
        'closestNeighbourScientificName': 'Cacatua',
        'region': 'WesternAustralia',
        'latitude': '-31.9505',  # Latitude for Perth, Australia
        'longitude': '115.8605',  # Longitude for Perth, Australia
        'threatName': 'Pesticide Poisoning',
        'threatDescription': 'Contamination of food sources due to pesticide use.',
        'severity': 3,
        'organizationName': 'Western Australian Parrot Conservation',
        'projectDescription': 'Conservation project for galah habitats.',
        'startDate': '2022-01-01',
        'endDate': '2024-01-01',
        'cloclatitude': '-31.9505',  # Latitude for Perth, Australia
        'cloclongitude': '115.8605',  # Longitude for Perth, Australia
        'cloccountry': 'Australia',
        'clocregion': 'WesternAustralia',
        'conservationPark': 'Coastal Eucalyptus Reserve'
    },
    {
        'commonName': 'Tasmanian Devil',
        'scientificName': 'Sarcophilus harrisii',
        'populationSize': 5000,
        'description': 'The Tasmanian devil is a carnivorous marsupial found only on the island of Tasmania.',
        'estimatedExtinctionDate': '2050-01-01',
        'closestNeighbourCommonName': 'Quoll',
        'closestNeighbourScientificName': 'Dasyurus',
        'region': 'Tasmania',
        'latitude': '-42.8821',  # Latitude for Hobart, Australia
        'longitude': '147.3272',  # Longitude for Hobart, Australia
        'threatName': 'Devil Facial Tumor Disease',
        'threatDescription': 'Contagious cancer affecting Tasmanian devil populations.',
        'severity': 5,
        'organizationName': 'Tasmanian Wildlife Conservation Society',
        'projectDescription': 'Conservation project for Tasmanian devil health.',
        'startDate': '2022-01-01',
        'endDate': '2023-12-31',
        'cloclatitude': '-42.8821',  # Latitude for Hobart, Australia
        'cloclongitude': '147.3272',  # Longitude for Hobart, Australia
        'cloccountry': 'Australia',
        'clocregion': 'Tasmania',
        'conservationPark': 'Tasmanian Wilderness Sanctuary'
    },
    {
        'commonName': 'Numbat',
        'scientificName': 'Myrmecobius fasciatus',
        'populationSize': 1000,
        'description': 'The numbat is a small marsupial native to Western Australia.',
        'estimatedExtinctionDate': '2048-01-01',
        'closestNeighbourCommonName': 'Bilby',
        'closestNeighbourScientificName': 'Macrotis lagotis',
        'region': 'WesternAustralia',
        'latitude': '-31.9505',  # Latitude for Perth, Australia
        'longitude': '115.8605',  # Longitude for Perth, Australia
        'threatName': 'Predation',
        'threatDescription': 'Threats from introduced predators impacting numbat populations.',
        'severity': 4,
        'organizationName': 'Western Australian Wildlife Preservation',
        'projectDescription': 'Conservation project for numbat habitats.',
        'startDate': '2022-01-01',
        'endDate': '2025-01-01',
        'cloclatitude': '-31.9505',  # Latitude for Perth, Australia
        'cloclongitude': '115.8605',  # Longitude for Perth, Australia
        'cloccountry': 'Australia',
        'clocregion': 'WesternAustralia',
        'conservationPark': 'Numbat Nature Reserve'
    },
    {
        'commonName': 'Leadbeater\'s Possum',
        'scientificName': 'Gymnobelideus leadbeateri',
        'populationSize': 2000,
        'description': 'Leadbeater\'s possum is a critically endangered marsupial native to Victoria.',
        'estimatedExtinctionDate': '2040-01-01',
        'closestNeighbourCommonName': 'Squirrel Glider',
        'closestNeighbourScientificName': 'Petaurus norfolcensis',
        'region': 'Victoria',
        'latitude': '-37.8136',  # Latitude for Melbourne, Australia
        'longitude': '144.9631',  # Longitude for Melbourne, Australia
        'threatName': 'Habitat Fragmentation',
        'threatDescription': 'Loss and fragmentation of habitat impacting possum populations.',
        'severity': 5,
        'organizationName': 'Victorian Wildlife Preservation Society',
        'projectDescription': 'Conservation project for Leadbeater\'s possum.',
        'startDate': '2022-01-01',
        'endDate': '2024-01-01',
        'cloclatitude': '-37.8136',  # Latitude for Melbourne, Australia
        'cloclongitude': '144.9631',  # Longitude for Melbourne, Australia
        'cloccountry': 'Australia',
        'clocregion': 'Victoria',
        'conservationPark': 'Leadbeater\'s Possum Conservation Area'
    }, 
    {
        'commonName': 'Western Swamp Tortoise',
        'scientificName': 'Pseudemydura umbrina',
        'populationSize': 50,
        'description': 'A critically endangered freshwater turtle found in Western Australia.',
        'estimatedExtinctionDate': '2035-01-01',
        'closestNeighbourCommonName': 'Long-necked Turtle',
        'closestNeighbourScientificName': 'Chelodina oblonga',
        'region': 'WesternAustralia',
        'latitude': '-31.9505',  # Latitude for Perth, Australia
        'longitude': '115.8605',  # Longitude for Perth, Australia
        'threatName': 'Habitat Loss and Predation',
        'threatDescription': 'Habitat destruction and predation impacting tortoise populations.',
        'severity': 5,
        'organizationName': 'Western Australian Turtle Conservation Society',
        'projectDescription': 'Conservation project for Western Swamp Tortoise.',
        'startDate': '2022-01-01',
        'endDate': '2024-01-01',
        'cloclatitude': '-31.9505',  # Latitude for Perth, Australia
        'cloclongitude': '115.8605',  # Longitude for Perth, Australia
        'cloccountry': 'Australia',
        'clocregion': 'WesternAustralia',
        'conservationPark': 'Western Swamp Tortoise Conservation Area'
    },
    {
        'commonName': 'Regent Honeyeater',
        'scientificName': 'Anthochaera phrygia',
        'populationSize': 400,
        'description': 'The regent honeyeater is a critically endangered bird known for its distinctive markings.',
        'estimatedExtinctionDate': '2040-01-01',
        'closestNeighbourCommonName': 'Swift Parrot',
        'closestNeighbourScientificName': 'Lathamus discolor',
        'region': 'New South Wales',
        'latitude': '-32.7157',  # Latitude for Sydney, Australia
        'longitude': '152.147',  # Longitude for Sydney, Australia
        'threatName': 'Habitat Loss and Fragmentation',
        'threatDescription': 'Loss and fragmentation of woodlands impacting honeyeater populations.',
        'severity': 4,
        'organizationName': 'New South Wales Bird Conservation Group',
        'projectDescription': 'Conservation project for regent honeyeaters.',
        'startDate': '2022-01-01',
        'endDate': '2024-01-01',
        'cloclatitude': '-32.7157',  # Latitude for Sydney, Australia
        'cloclongitude': '152.147',  # Longitude for Sydney, Australia
        'cloccountry': 'Australia',
        'clocregion': 'NewSouthWales',
        'conservationPark': 'Regent Honeyeater Reserve'
    },
    {
        'commonName': 'Giant Gippsland Earthworm',
        'scientificName': 'Megascolides australis',
        'populationSize': 2000,
        'description': 'The giant Gippsland earthworm is one of the largest earthworms in the world.',
        'estimatedExtinctionDate': '2043-01-01',
        'closestNeighbourCommonName': 'Common Eastern Earthworm',
        'closestNeighbourScientificName': 'Aporrectodea longa',
        'region': 'Victoria',
        'latitude': '-38.1368',  # Latitude for Gippsland, Victoria, Australia
        'longitude': '146.4309',  # Longitude for Gippsland, Victoria, Australia
        'threatName': 'Habitat Destruction',
        'threatDescription': 'Loss of habitat due to human development impacting earthworm populations.',
        'severity': 5,
        'organizationName': 'Victorian Earthworm Conservation Society',
        'projectDescription': 'Conservation project for the giant Gippsland earthworm.',
        'startDate': '2022-01-01',
        'endDate': '2024-01-01',
        'cloclatitude': '-38.1368',  # Latitude for Gippsland, Victoria, Australia
        'cloclongitude': '146.4309',  # Longitude for Gippsland, Victoria, Australia
        'cloccountry': 'Australia',
        'clocregion': 'Victoria',
        'conservationPark': 'Gippsland Earthworm Sanctuary'
    },
    {
        'commonName': 'Gouldian Finch',
        'scientificName': 'Erythrura gouldiae',
        'populationSize': 2500,
        'description': 'The Gouldian finch is a brightly colored bird found in Northern Australia.',
        'estimatedExtinctionDate': '2046-01-01',
        'closestNeighbourCommonName': 'Zebra Finch',
        'closestNeighbourScientificName': 'Taeniopygia guttata',
        'region': 'NorthernTerritory',
        'latitude': '-12.4634',  # Latitude for Darwin, Northern Territory, Australia
        'longitude': '130.8456',  # Longitude for Darwin, Northern Territory, Australia
        'threatName': 'Habitat Fragmentation',
        'threatDescription': 'Fragmentation of grassland habitats impacting Gouldian finch populations.',
        'severity': 4,
        'organizationName': 'Northern Territory Finch Preservation Society',
        'projectDescription': 'Conservation project for the Gouldian finch.',
        'startDate': '2022-01-01',
        'endDate': '2025-01-01',
        'cloclatitude': '-12.4634',  # Latitude for Darwin, Northern Territory, Australia
        'cloclongitude': '130.8456',  # Longitude for Darwin, Northern Territory, Australia
        'cloccountry': 'Australia',
        'clocregion': 'NorthernTerritory',
        'conservationPark': 'Gouldian Finch Reserve'
    },
    {
        'commonName': 'Bilby',
        'scientificName': 'Macrotis lagotis',
        'populationSize': 500,
        'description': 'The bilby is a small marsupial known for its long ears and burrowing habits.',
        'estimatedExtinctionDate': '2050-01-01',
        'closestNeighbourCommonName': 'Numbat',
        'closestNeighbourScientificName': 'Myrmecobius fasciatus',
        'region': 'NorthernTerritory',
        'latitude': '-12.4634',  # Latitude for Darwin, Northern Territory, Australia
        'longitude': '130.8456',  # Longitude for Darwin, Northern Territory, Australia
        'threatName': 'Predation and Habitat Loss',
        'threatDescription': 'Introduced predators and habitat destruction impacting bilby populations.',
        'severity': 4,
        'organizationName': 'Northern Territory Bilby Conservation Society',
        'projectDescription': 'Conservation project for the bilby population.',
        'startDate': '2022-01-01',
        'endDate': '2024-01-01',
        'cloclatitude': '-12.4634',  # Latitude for Darwin, Northern Territory, Australia
        'cloclongitude': '130.8456',  # Longitude for Darwin, Northern Territory, Australia
        'cloccountry': 'Australia',
        'clocregion': 'NorthernTerritory',
        'conservationPark': 'Bilby Protection Area'
    },
    {
        'commonName': 'Golden Bandicoot',
        'scientificName': 'Isoodon auratus',
        'populationSize': 600,
        'description': 'The golden bandicoot is a small marsupial with distinctive golden fur.',
        'estimatedExtinctionDate': '2048-01-01',
        'closestNeighbourCommonName': 'Northern Brown Bandicoot',
        'closestNeighbourScientificName': 'Isoodon macrourus',
        'region': 'NorthernTerritory',
        'latitude': '-12.4634',  # Latitude for Darwin, Northern Territory, Australia
        'longitude': '130.8456',  # Longitude for Darwin, Northern Territory, Australia
        'threatName': 'Habitat Fragmentation and Invasive Species',
        'threatDescription': 'Habitat fragmentation and invasive species impacting bandicoot habitats.',
        'severity': 3,
        'organizationName': 'Northern Territory Bandicoot Conservation Alliance',
        'projectDescription': 'Conservation project for the golden bandicoot.',
        'startDate': '2022-01-01',
        'endDate': '2025-01-01',
        'cloclatitude': '-12.4634',  # Latitude for Darwin, Northern Territory, Australia
        'cloclongitude': '130.8456',  # Longitude for Darwin, Northern Territory, Australia
        'cloccountry': 'Australia',
        'clocregion': 'NorthernTerritory',
        'conservationPark': 'Golden Bandicoot Sanctuary'
    },
    {
        'commonName': 'Helmeted Honeyeater',
        'scientificName': 'Lichenostomus melanops cassidix',
        'populationSize': 250,
        'description': 'The helmeted honeyeater is a critically endangered bird endemic to Victoria.',
        'estimatedExtinctionDate': '2045-01-01',
        'closestNeighbourCommonName': 'Yellow-tufted Honeyeater',
        'closestNeighbourScientificName': 'Lichenostomus melanops',
        'region': 'Victoria',
        'latitude': '-37.8136',  # Latitude for Melbourne, Victoria, Australia
        'longitude': '144.9631',  # Longitude for Melbourne, Victoria, Australia
        'threatName': 'Habitat Loss and Predation',
        'threatDescription': 'Loss of habitat and predation impacting helmeted honeyeater populations.',
        'severity': 5,
        'organizationName': 'Victorian Helmeted Honeyeater Preservation Society',
        'projectDescription': 'Conservation project for the helmeted honeyeater.',
        'startDate': '2022-01-01',
        'endDate': '2024-01-01',
        'cloclatitude': '-37.8136',  # Latitude for Melbourne, Victoria, Australia
        'cloclongitude': '144.9631',  # Longitude for Melbourne, Victoria, Australia
        'cloccountry': 'Australia',
        'clocregion': 'Victoria',
        'conservationPark': 'Helmeted Honeyeater Reserve'
    },
    {
        'commonName': 'Mallee Fowl',
        'scientificName': 'Leipoa ocellata',
        'populationSize': 300,
        'description': 'The Mallee fowl is a ground-dwelling bird known for its large nesting mounds.',
        'estimatedExtinctionDate': '2049-01-01',
        'closestNeighbourCommonName': 'Brush Bronzewing',
        'closestNeighbourScientificName': 'Phaps elegans',
        'region': 'SouthAustralia',
        'latitude': '-34.9285',  # Latitude for Adelaide, South Australia, Australia
        'longitude': '138.6007',  # Longitude for Adelaide, South Australia, Australia
        'threatName': 'Habitat Degradation and Predation',
        'threatDescription': 'Habitat degradation and introduced predators affecting Mallee fowl habitats.',
        'severity': 4,
        'organizationName': 'South Australian Mallee Fowl Conservation Group',
        'projectDescription': 'Conservation project for the Mallee fowl.',
        'startDate': '2022-01-01',
        'endDate': '2025-01-01',
        'cloclatitude': '-34.9285',  # Latitude for Adelaide, South Australia, Australia
        'cloclongitude': '138.6007',  # Longitude for Adelaide, South Australia, Australia
        'cloccountry': 'Australia',
        'clocregion': 'SouthAustralia',
        'conservationPark': 'Mallee Fowl Habitat Preservation Area'
    },
    {
        'commonName': 'Night Parrot',
        'scientificName': 'Pezoporus occidentalis',
        'populationSize': 50,
        'description': 'The night parrot is an elusive and rarely seen nocturnal bird.',
        'estimatedExtinctionDate': '2050-01-01',
        'closestNeighbourCommonName': 'Bourke\'s Parrot',
        'closestNeighbourScientificName': 'Neopsephotus bourkii',
        'region': 'WesternAustralia',
        'latitude': '-31.9505',  # Latitude for Perth, Western Australia, Australia
        'longitude': '115.8605',  # Longitude for Perth, Western Australia, Australia
        'threatName': 'Habitat Loss and Feral Predators',
        'threatDescription': 'Habitat loss and feral predators impacting night parrot populations.',
        'severity': 5,
        'organizationName': 'Western Australian Night Parrot Conservancy',
        'projectDescription': 'Conservation project for the night parrot.',
        'startDate': '2022-01-01',
        'endDate': '2024-01-01',
        'cloclatitude': '-31.9505',  # Latitude for Perth, Western Australia, Australia
        'cloclongitude': '115.8605',  # Longitude for Perth, Western Australia, Australia
        'cloccountry': 'Australia',
        'clocregion': 'WesternAustralia',
        'conservationPark': 'Night Parrot Conservation Reserve'
    },
    {
        'commonName': 'Central Rock Rat',
        'scientificName': 'Zyzomys pedunculatus',
        'populationSize': 100,
        'description': 'The central rock rat is a small, rare rodent species.',
        'estimatedExtinctionDate': '2046-01-01',
        'closestNeighbourCommonName': 'Fawn Hopping Mouse',
        'closestNeighbourScientificName': 'Notomys cervinus',
        'region': 'NorthernTerritory',
        'latitude': '-12.4634',  # Latitude for Darwin, Northern Territory, Australia
        'longitude': '130.8456',  # Longitude for Darwin, Northern Territory, Australia
        'threatName': 'Habitat Fragmentation and Predation',
        'threatDescription': 'Habitat fragmentation and predation impacting central rock rat populations.',
        'severity': 4,
        'organizationName': 'Northern Territory Rock Rat Conservation Society',
        'projectDescription': 'Conservation project for the central rock rat.',
        'startDate': '2022-01-01',
        'endDate': '2024-01-01',
        'cloclatitude': '-12.4634',  # Latitude for Darwin, Northern Territory, Australia
        'cloclongitude': '130.8456',  # Longitude for Darwin, Northern Territory, Australia
        'cloccountry': 'Australia',
        'clocregion': 'NorthernTerritory',
        'conservationPark': 'Central Rock Rat Protection Area'
    },
    {
        'commonName': 'Quokka',
        'scientificName': 'Setonix brachyurus',
        'populationSize': 15000,
        'description': 'The quokka is a small marsupial known for its friendly appearance and smile.',
        'estimatedExtinctionDate': '2040-01-01',
        'closestNeighbourCommonName': 'Coastal Taipan',
        'closestNeighbourScientificName': 'Oxyuranus scutellatus',
        'region': 'NorthernTerritory',
        'latitude': '-12.4634',  # Latitude for Darwin, Northern Territory, Australia
        'longitude': '130.8456',  # Longitude for Darwin, Northern Territory, Australia
        'threatName': 'Habitat Destruction and Human Encroachment',
        'threatDescription': 'Habitat destruction and human encroachment impacting Central Ranges taipan populations.',
        'severity': 5,
        'organizationName': 'Northern Territory Taipan Conservation Group',
        'projectDescription': 'Conservation project for the Central Ranges taipan.',
        'startDate': '2022-01-01',
        'endDate': '2024-01-01',
        'cloclatitude': '-12.4634',  # Latitude for Darwin, Northern Territory, Australia
        'cloclongitude': '130.8456',  # Longitude for Darwin, Northern Territory, Australia
        'cloccountry': 'Australia',
        'clocregion': 'NorthernTerritory',
        'conservationPark': 'Central Ranges Taipan Sanctuary'
    },
    {
        'commonName': 'Eastern Curlew',
        'scientificName': 'Numenius madagascariensis',
        'populationSize': 20000,
        'description': 'A large migratory shorebird facing threats from habitat loss and degradation due to coastal development and disturbances in its feeding and breeding grounds.',
        'estimatedExtinctionDate': '2045-01-01',
        'closestNeighbourCommonName': 'Humphead Wrasse',
        'closestNeighbourScientificName': 'Cheilinus undulatus',
        'region': 'Coastal Areas',
        'latitude': '-33.8600',  # Approximate latitude for coastal areas in Australia
        'longitude': '151.2094',  # Approximate longitude for coastal areas in Australia
        'threatName': 'Habitat Loss and Coastal Development',
        'threatDescription': 'Coastal development and disturbances impacting the Eastern Curlew habitats.',
        'severity': 4,
        'organizationName': 'Shorebird Conservation Society',
        'projectDescription': 'Conservation project aimed at protecting shorebirds and their habitats.',
        'startDate': '2023-01-01',
        'endDate': '2026-01-01',
        'cloclatitude': '-33.8600',  # Approximate latitude for coastal areas in Australia
        'cloclongitude': '151.2094',  # Approximate longitude for coastal areas in Australia
        'cloccountry': 'Australia',
        'clocregion': 'CoastalAreas',
        'conservationPark': 'Shorebird Haven Conservation Park'
    },
    {
        'commonName': 'Hawksbill Turtle',
        'scientificName': 'Eretmochelys imbricata',
        'populationSize': 15000,
        'description': 'Found in the Great Barrier Reef and coastal areas, this sea turtle species is endangered due to habitat loss, hunting for their shells, and accidental capture in fishing gear.',
        'estimatedExtinctionDate': '2040-01-01',
        'closestNeighbourCommonName': 'Dugong',
        'closestNeighbourScientificName': 'Dugong dugon',
        'region': 'Great Barrier Reef',
        'latitude': '-16.9211',  # Approximate latitude for the Great Barrier Reef in Australia
        'longitude': '145.7800',  # Approximate longitude for the Great Barrier Reef in Australia
        'threatName': 'Habitat Loss and Hunting',
        'threatDescription': 'Habitat loss and hunting posing significant threats to Hawksbill Turtle populations.',
        'severity': 5,
        'organizationName': 'Great Barrier Reef Conservation Society',
        'projectDescription': 'Conservation efforts to protect sea turtles and their habitats.',
        'startDate': '2022-01-01',
        'endDate': '2025-01-01',
        'cloclatitude': '-16.9211',  # Approximate latitude for the Great Barrier Reef in Australia
        'cloclongitude': '145.7800',  # Approximate longitude for the Great Barrier Reef in Australia
        'cloccountry': 'Australia',
        'clocregion': 'GreatBarrierReef',
        'conservationPark': 'Turtle Reef Conservation Park'
    },
    {
        'commonName': 'Swift Parrot',
        'scientificName': 'Lathamus discolor',
        'populationSize': 8000,
        'description': 'Colorful migratory parrots threatened by habitat loss caused by deforestation, land clearing, and competition for nesting sites with introduced species.',
        'estimatedExtinctionDate': '2038-01-01',
        'closestNeighbourCommonName': 'Rainbow Lorikeet',
        'closestNeighbourScientificName': 'Trichoglossus moluccanus',
        'region': 'Tasmania',
        'latitude': '-41.4545',  # Approximate latitude for Tasmania in Australia
        'longitude': '145.9707',  # Approximate longitude for Tasmania in Australia
        'threatName': 'Deforestation and Nesting Site Competition',
        'threatDescription': 'Deforestation and competition for nesting sites posing threats to Swift Parrot populations.',
        'severity': 4,
        'organizationName': 'Tasmanian Bird Conservancy',
        'projectDescription': 'Conservation project focusing on protecting Swift Parrots and their habitats.',
        'startDate': '2023-01-01',
        'endDate': '2027-01-01',
        'cloclatitude': '-41.4545',  # Approximate latitude for Tasmania in Australia
        'cloclongitude': '145.9707',  # Approximate longitude for Tasmania in Australia
        'cloccountry': 'Australia',
        'clocregion': 'Tasmania',
        'conservationPark': 'Parrot Paradise Conservation Park'
    },
    {
        'commonName': 'Gilbert\'s Potoroo',
        'scientificName': 'Potorous gilbertii',
        'populationSize': 500,
        'description': 'One of Australia\'s most endangered marsupials facing threats from habitat destruction and predation by introduced predators.',
        'estimatedExtinctionDate': '2037-01-01',
        'closestNeighbourCommonName': 'Quokka',
        'closestNeighbourScientificName': 'Setonix brachyurus',
        'region': 'Western Australia',
        'latitude': '-25.2744',  # Approximate latitude for Western Australia in Australia
        'longitude': '133.7751',  # Approximate longitude for Western Australia in Australia
        'threatName': 'Habitat Destruction and Predation',
        'threatDescription': 'Habitat destruction and predation by introduced species impacting Gilbert\'s Potoroo populations.',
        'severity': 5,
        'organizationName': 'Western Australia Wildlife Protection',
        'projectDescription': 'Conservation efforts focused on saving Gilbert\'s Potoroo and restoring their habitats.',
        'startDate': '2022-01-01',
        'endDate': '2026-01-01',
        'cloclatitude': '-25.2744',  # Approximate latitude for Western Australia in Australia
        'cloclongitude': '133.7751',  # Approximate longitude for Western Australia in Australia
        'cloccountry': 'Australia',
        'clocregion': 'WesternAustralia',
        'conservationPark': 'Potoroo Preserve Conservation Park'
    },
    {
        'commonName': 'Mahogany Glider',
        'scientificName': 'Petaurus gracilis',
        'populationSize': 3000,
        'description': 'Endemic to Queensland\'s coastal forests, this gliding possum is threatened by habitat fragmentation and loss due to land clearing for agriculture and urban development.',
        'estimatedExtinctionDate': '2042-01-01',
        'closestNeighbourCommonName': 'Northern Bettong',
        'closestNeighbourScientificName': 'Bettongia tropica',
        'region': 'Queensland',
        'latitude': '-20.9176',  # Approximate latitude for Queensland in Australia
        'longitude': '142.7028',  # Approximate longitude for Queensland in Australia
        'threatName': 'Habitat Fragmentation and Urban Development',
        'threatDescription': 'Habitat fragmentation and urban development causing a decline in Mahogany Glider populations.',
        'severity': 4,
        'organizationName': 'Queensland Wildlife Conservation Alliance',
        'projectDescription': 'Conservation initiatives aimed at protecting Mahogany Gliders and preserving their habitats.',
        'startDate': '2022-01-01',
        'endDate': '2025-01-01',
        'cloclatitude': '-20.9176',  # Approximate latitude for Queensland in Australia
        'cloclongitude': '142.7028',  # Approximate longitude for Queensland in Australia
        'cloccountry': 'Australia',
        'clocregion': 'Queensland',
        'conservationPark': 'Gliding Possum Grove Conservation Park'
    },
    {
        "commonName": "Northern Hairy-Nosed Wombat",
        "scientificName": "Lasiorhinus krefftii",
        'populationSize': 15000,
        "description": "A critically endangered species with a small population in Queensland.",
        "estimatedExtinctionDate": "2040-01-01",
        "closestNeighbourCommonName": "Southern Hairy-Nosed Wombat",
        "closestNeighbourScientificName": "Lasiorhinus latifrons",
        "region": "Queensland",
        "latitude": "-24.8697",
        "longitude": "133.2197",
        "threatName": "Habitat Fragmentation",
        "threatDescription": "Loss of habitat due to agriculture and invasive species.",
        "severity": 5,
        "organizationName": "Queensland Wildlife Conservation Society",
        "projectDescription": "Focused on habitat restoration and predator control.",
        "startDate": "2023-02-01",
        "endDate": "2027-02-01",
        "cloclatitude": "-24.8697",
        "cloclongitude": "133.2197",
        "cloccountry": "Australia",
        "clocregion": "Queensland",
        "conservationPark": "Wombat Sanctuary Reserve"
    },
    {
        "commonName": "Greater Stick-Nest Rat",
        "scientificName": "Leporillus conditor",
        'populationSize': 160000,
        "description": "An endangered rodent known for building complex stick-nests.",
        "estimatedExtinctionDate": "2043-01-01",
        "closestNeighbourCommonName": "Rufous Hare-Wallaby",
        "closestNeighbourScientificName": "Lagorchestes hirsutus",
        "region": "SouthAustralia",
        "latitude": "-30.0002",
        "longitude": "136.2092",
        "threatName": "Predation",
        "threatDescription": "Predation by feral cats and foxes is a significant threat.",
        "severity": 4,
        "organizationName": "South Australian Wildlife Preservation Society",
        "projectDescription": "Focused on predator control and habitat protection.",
        "startDate": "2022-11-01",
        "endDate": "2026-11-01",
        "cloclatitude": "-30.0002",
        "cloclongitude": "136.2092",
        "cloccountry": "Australia",
        "clocregion": "SouthAustralia",
        "conservationPark": "Stick-Nest Rat Sanctuary"
    },
    {
        "commonName": "Western Ground Parrot",
        "scientificName": "Pezoporus flaviventris",
        'populationSize': 30000,
        "description": "A rare parrot species endemic to Western Australia.",
        "estimatedExtinctionDate": "2044-01-01",
        "closestNeighbourCommonName": "Red-capped Parrot",
        "closestNeighbourScientificName": "Purpureicephalus spurius",
        "region": "WesternAustralia",
        "latitude": "-25.0478",
        "longitude": "134.0036",
        "threatName": "Habitat Loss",
        "threatDescription": "Loss of habitat due to fire and land clearing.",
        "severity": 4,
        "organizationName": "Western Australian Parrot Conservation Group",
        "projectDescription": "Efforts focused on fire management and habitat restoration.",
        "startDate": "2023-04-01",
        "endDate": "2027-04-01",
        "cloclatitude": "-25.0478",
        "cloclongitude": "134.0036",
        "cloccountry": "Australia",
        "clocregion": "WesternAustralia",
        "conservationPark": "Ground Parrot Conservation Reserve"
    },
    {
        "commonName": "Eastern Barred Bandicoot",
        "scientificName": "Perameles gunnii",
        'populationSize': 12000,
        "description": "A critically endangered bandicoot species found in Victoria.",
        "estimatedExtinctionDate": "2041-01-01",
        "closestNeighbourCommonName": "Long-Nosed Bandicoot",
        "closestNeighbourScientificName": "Perameles nasuta",
        "region": "Victoria",
        "latitude": "-37.4713",
        "longitude": "144.7852",
        "threatName": "Predation",
        "threatDescription": "Predation by foxes and habitat loss are major threats.",
        "severity": 5,
        "organizationName": "Victorian Bandicoot Conservation Trust",
        "projectDescription": "Focused on predator control and habitat restoration.",
        "startDate": "2022-10-01",
        "endDate": "2026-10-01",
        "cloclatitude": "-37.4713",
        "cloclongitude": "144.7852",
        "cloccountry": "Australia",
        "clocregion": "Victoria",
        "conservationPark": "Barred Bandicoot Sanctuary"
    },
    {
        "commonName": "Western Swamp Tortoise",
        "scientificName": "Pseudemydura umbrina",
        'populationSize': 32000,
        "description": "A critically endangered tortoise species in Western Australia.",
        "estimatedExtinctionDate": "2042-01-01",
        "closestNeighbourCommonName": "Long-Necked Turtle",
        "closestNeighbourScientificName": "Chelodina longicollis",
        "region": "WesternAustralia",
        "latitude": "-31.8229",
        "longitude": "116.0037",
        "threatName": "Habitat Loss",
        "threatDescription": "Loss of wetland habitats due to urban development.",
        "severity": 4,
        "organizationName": "Western Australian Tortoise Conservation Society",
        "projectDescription": "Focused on wetland restoration and captive breeding programs.",
        "startDate": "2023-06-01",
        "endDate": "2027-06-01",
        "cloclatitude": "-31.8229",
        "cloclongitude": "116.0037",
        "cloccountry": "Australia",
        "clocregion": "WesternAustralia",
        "conservationPark": "Swamp Tortoise Conservation Area"
    },
    {
        "commonName": "Southern Corroboree Frog",
        "scientificName": "Pseudophryne corroboree",
        'populationSize': 180000,
        "description": "A critically endangered frog species found in alpine regions.",
        "estimatedExtinctionDate": "2043-01-01",
        "closestNeighbourCommonName": "Northern Corroboree Frog",
        "closestNeighbourScientificName": "Pseudophryne pengilleyi",
        "region": "NewSouthWales",
        "latitude": "-36.3830",
        "longitude": "148.6039",
        "threatName": "Chytrid Fungus",
        "threatDescription": "Susceptible to the lethal chytrid fungus affecting amphibians.",
        "severity": 5,
        "organizationName": "New South Wales Frog Conservation Alliance",
        "projectDescription": "Focused on disease management and habitat protection.",
        "startDate": "2022-12-01",
        "endDate": "2026-12-01",
        "cloclatitude": "-36.3830",
        "cloclongitude": "148.6039",
        "cloccountry": "Australia",
        "clocregion": "NewSouthWales",
        "conservationPark": "Corroboree Frog Reserve"
    },
    {
        "commonName": "Red Goshawk",
        "scientificName": "Erythrotriorchis radiatus",
        'populationSize': 37000,
        "description": "An endangered raptor species with a restricted distribution.",
        "estimatedExtinctionDate": "2045-01-01",
        "closestNeighbourCommonName": "Brown Goshawk",
        "closestNeighbourScientificName": "Accipiter fasciatus",
        "region": "NorthernTerritory",
        "latitude": "-12.4634",
        "longitude": "130.8456",
        "threatName": "Habitat Loss",
        "threatDescription": "Loss of suitable habitat due to land clearing and logging.",
        "severity": 4,
        "organizationName": "Northern Territory Raptor Conservation Group",
        "projectDescription": "Focused on protecting nesting sites and habitat conservation.",
        "startDate": "2023-01-01",
        "endDate": "2027-01-01",
        "cloclatitude": "-12.4634",
        "cloclongitude": "130.8456",
        "cloccountry": "Australia",
        "clocregion": "NorthernTerritory",
        "conservationPark": "Red Goshawk Sanctuary"
    },
    {
        "commonName": "Giant Burrowing Frog",
        "scientificName": "Heleioporus australiacus",
        'populationSize': 3000,
        "description": "An endangered amphibian known for its burrowing behavior.",
        "estimatedExtinctionDate": "2042-01-01",
        "closestNeighbourCommonName": "Spotted Grass Frog",
        "closestNeighbourScientificName": "Limnodynastes tasmaniensis",
        "region": "Victoria",
        "latitude": "-37.4713",
        "longitude": "144.7852",
        "threatName": "Habitat Destruction",
        "threatDescription": "Loss of habitat due to urbanization and pollution.",
        "severity": 4,
        "organizationName": "Victorian Frog Conservation Society",
        "projectDescription": "Focused on wetland restoration and pollution control.",
        "startDate": "2022-09-01",
        "endDate": "2026-09-01",
        "cloclatitude": "-37.4713",
        "cloclongitude": "144.7852",
        "cloccountry": "Australia",
        "clocregion": "Victoria",
        "conservationPark": "Burrowing Frog Reserve"
    },
    {
        "commonName": "Pygmy Bluetongue Lizard",
        "scientificName": "Tiliqua adelaidensis",
        'populationSize': 30000,
        "description": "A small and rare lizard species found in South Australia.",
        "estimatedExtinctionDate": "2043-01-01",
        "closestNeighbourCommonName": "Eastern Bluetongue Lizard",
        "closestNeighbourScientificName": "Tiliqua scincoides",
        "region": "SouthAustralia",
        "latitude": "-30.0002",
        "longitude": "136.2092",
        "threatName": "Habitat Loss",
        "threatDescription": "Habitat degradation due to land clearing and urban expansion.",
        "severity": 4,
        "organizationName": "South Australian Lizard Conservation Alliance",
        "projectDescription": "Focused on habitat protection and captive breeding.",
        "startDate": "2023-05-01",
        "endDate": "2027-05-01",
        "cloclatitude": "-30.0002",
        "cloclongitude": "136.2092",
        "cloccountry": "Australia",
        "clocregion": "SouthAustralia",
        "conservationPark": "Bluetongue Lizard Habitat Reserve"
    },
    {
        "commonName": "Western Ringtail Possum",
        "scientificName": "Pseudocheirus occidentalis",
        'populationSize': 15000,
        "description": "A critically endangered possum species in Western Australia.",
        "estimatedExtinctionDate": "2044-01-01",
        "closestNeighbourCommonName": "Common Ringtail Possum",
        "closestNeighbourScientificName": "Pseudocheirus peregrinus",
        "region": "WesternAustralia",
        "latitude": "-31.8229",
        "longitude": "116.0037",
        "threatName": "Habitat Fragmentation",
        "threatDescription": "Fragmentation due to urbanization and habitat loss.",
        "severity": 5,
        "organizationName": "Western Australian Possum Conservation Society",
        "projectDescription": "Protection of remaining habitats and breeding programs.",
        "startDate": "2023-07-01",
        "endDate": "2027-07-01",
        "cloclatitude": "-31.8229",
        "cloclongitude": "116.0037",
        "cloccountry": "Australia",
        "clocregion": "WesternAustralia",
        "conservationPark": "Ringtail Possum Sanctuary"
    },
    {
        "commonName": "Glossy Black Cockatoo",
        "scientificName": "Calyptorhynchus lathami",
        'populationSize': 36000,
        "description": "An endangered cockatoo species with distinct glossy plumage.",
        "estimatedExtinctionDate": "2042-01-01",
        "closestNeighbourCommonName": "Yellow-Tailed Black Cockatoo",
        "closestNeighbourScientificName": "Calyptorhynchus funereus",
        "region": "NewSouthWales",
        "latitude": "-33.8688",
        "longitude": "151.2093",
        "threatName": "Habitat Loss",
        "threatDescription": "Loss of habitat due to deforestation and land clearing.",
        "severity": 4,
        "organizationName": "New South Wales Cockatoo Conservation Alliance",
        "projectDescription": "Focused on preserving nesting sites and habitat restoration.",
        "startDate": "2023-02-01",
        "endDate": "2027-02-01",
        "cloclatitude": "-33.8688",
        "cloclongitude": "151.2093",
        "cloccountry": "Australia",
        "clocregion": "NewSouthWales",
        "conservationPark": "Glossy Cockatoo Sanctuary"
    },
    {
        "commonName": "Southern Bent-Winged Bat",
        "scientificName": "Miniopterus schreibersii bassanii",
        'populationSize': 78000,
        "description": "An endangered microbat species with distinctive wing morphology.",
        "estimatedExtinctionDate": "2045-01-01",
        "closestNeighbourCommonName": "Eastern Bent-Winged Bat",
        "closestNeighbourScientificName": "Miniopterus schreibersii oceanensis",
        "region": "Victoria",
        "latitude": "-37.8136",
        "longitude": "144.9631",
        "threatName": "Habitat Disturbance",
        "threatDescription": "Disturbance of roosting sites due to human activities.",
        "severity": 5,
        "organizationName": "Victorian Bat Conservation Society",
        "projectDescription": "Focused on habitat protection and public awareness.",
        "startDate": "2023-09-01",
        "endDate": "2027-09-01",
        "cloclatitude": "-37.8136",
        "cloclongitude": "144.9631",
        "cloccountry": "Australia",
        "clocregion": "Victoria",
        "conservationPark": "Bent-Winged Bat Reserve"
    },
    {
        "commonName": "Western Quoll",
        "scientificName": "Dasyurus geoffroii",
        'populationSize': 125000,
        "description": "A critically endangered carnivorous marsupial with spotted fur.",
        "estimatedExtinctionDate": "2043-01-01",
        "closestNeighbourCommonName": "Tiger Quoll",
        "closestNeighbourScientificName": "Dasyurus maculatus",
        "region": "WesternAustralia",
        "latitude": "-24.8660",
        "longitude": "113.6567",
        "threatName": "Predation",
        "threatDescription": "Predation by introduced species such as foxes and cats.",
        "severity": 5,
        "organizationName": "Western Australian Quoll Conservation Trust",
        "projectDescription": "Focused on predator control and habitat preservation.",
        "startDate": "2023-01-01",
        "endDate": "2027-01-01",
        "cloclatitude": "-24.8660",
        "cloclongitude": "113.6567",
        "cloccountry": "Australia",
        "clocregion": "WesternAustralia",
        "conservationPark": "Quoll Habitat Reserve"
    },
    {
        "commonName": "Dibbler",
        "scientificName": "Parantechinus apicalis",
        'populationSize': 35000,
        "description": "A small marsupial known for its insectivorous diet.",
        "estimatedExtinctionDate": "2044-01-01",
        "closestNeighbourCommonName": "Fat-Tailed Dunnart",
        "closestNeighbourScientificName": "Sminthopsis crassicaudata",
        "region": "WesternAustralia",
        "latitude": "-32.0420",
        "longitude": "115.9235",
        "threatName": "Habitat Fragmentation",
        "threatDescription": "Fragmentation due to urbanization and land development.",
        "severity": 4,
        "organizationName": "Western Australian Dibbler Conservation Group",
        "projectDescription": "Focused on habitat connectivity and population monitoring.",
        "startDate": "2023-04-01",
        "endDate": "2027-04-01",
        "cloclatitude": "-32.0420",
        "cloclongitude": "115.9235",
        "cloccountry": "Australia",
        "clocregion": "WesternAustralia",
        "conservationPark": "Dibbler Conservation Area"
    },
    {
        "commonName": "Eastern Barred Bandicoot",
        "scientificName": "Perameles gunnii",
        'populationSize': 35000,
        "description": "A critically endangered bandicoot species found in Victoria.",
        "estimatedExtinctionDate": "2041-01-01",
        "closestNeighbourCommonName": "Long-Nosed Bandicoot",
        "closestNeighbourScientificName": "Perameles nasuta",
        "region": "Victoria",
        "latitude": "-37.4713",
        "longitude": "144.7852",
        "threatName": "Predation",
        "threatDescription": "Predation by foxes and habitat loss are major threats.",
        "severity": 5,
        "organizationName": "Victorian Bandicoot Conservation Trust",
        "projectDescription": "Focused on predator control and habitat restoration.",
        "startDate": "2022-10-01",
        "endDate": "2026-10-01",
        "cloclatitude": "-37.4713",
        "cloclongitude": "144.7852",
        "cloccountry": "Australia",
        "clocregion": "Victoria",
        "conservationPark": "Barred Bandicoot Sanctuary"
    },
    {
        "commonName": "Hooded Plover",
        "scientificName": "Thinornis cucullatus",
        'populationSize': 20000,
        "description": "A threatened shorebird species nesting along coastal areas.",
        "estimatedExtinctionDate": "2045-01-01",
        "closestNeighbourCommonName": "Red-Capped Plover",
        "closestNeighbourScientificName": "Charadrius ruficapillus",
        "region": "Tasmania",
        "latitude": "-42.8821",
        "longitude": "147.3272",
        "threatName": "Habitat Disturbance",
        "threatDescription": "Disturbance of nesting sites due to human activities and predation.",
        "severity": 4,
        "organizationName": "Tasmanian Shorebird Conservation Society",
        "projectDescription": "Focused on protecting nesting sites and habitat conservation.",
        "startDate": "2023-11-01",
        "endDate": "2027-11-01",
        "cloclatitude": "-42.8821",
        "cloclongitude": "147.3272",
        "cloccountry": "Australia",
        "clocregion": "Tasmania",
        "conservationPark": "Plover Nesting Area"
    },
    {
        "commonName": "Northern Quoll",
        "scientificName": "Dasyurus hallucatus",
        'populationSize': 160000,
        "description": "An endangered carnivorous marsupial species with a distinctive spotted coat.",
        "estimatedExtinctionDate": "2043-01-01",
        "closestNeighbourCommonName": "Spotted-Tailed Quoll",
        "closestNeighbourScientificName": "Dasyurus maculatus",
        "region": "NorthernTerritory",
        "latitude": "-19.4914",
        "longitude": "132.5509",
        "threatName": "Predation",
        "threatDescription": "Predation by invasive species such as cane toads.",
        "severity": 5,
        "organizationName": "Northern Territory Quoll Conservation Society",
        "projectDescription": "Focused on predator control and habitat restoration.",
        "startDate": "2023-03-01",
        "endDate": "2027-03-01",
        "cloclatitude": "-19.4914",
        "cloclongitude": "132.5509",
        "cloccountry": "Australia",
        "clocregion": "NorthernTerritory",
        "conservationPark": "Quoll Habitat Reserve"
    },
    {
        "commonName": "Gilbert's Whistler",
        "scientificName": "Pachycephala inornata",
        'populationSize': 3000,
        "description": "An endangered songbird species known for its melodious calls.",
        "estimatedExtinctionDate": "2046-01-01",
        "closestNeighbourCommonName": "Golden Whistler",
        "closestNeighbourScientificName": "Pachycephala pectoralis",
        "region": "NorthernTerritory",
        "latitude": "-12.4634",
        "longitude": "130.8456",
        "threatName": "Habitat Fragmentation",
        "threatDescription": "Fragmentation due to land clearing and habitat degradation.",
        "severity": 4,
        "organizationName": "Northern Territory Bird Conservation Society",
        "projectDescription": "Focused on preserving remaining habitats and population monitoring.",
        "startDate": "2023-10-01",
        "endDate": "2027-10-01",
        "cloclatitude": "-12.4634",
        "cloclongitude": "130.8456",
        "cloccountry": "Australia",
        "clocregion": "NorthernTerritory",
        "conservationPark": "Whistler Habitat Reserve"
    }    
]


def get_random_dummy_data():
    return random.choice(dummy_data_list)
